name: Build and Deploy to Github Pages
$NOTION_TOKEN: secret_BiokHV3wX3KhaIVzUg34cxteDKkNX9kG3Ut7hnfepCA

on:
  push:
    branches:
      - master  # Here source code branch is `master`, it could be other branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@master
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          repository: ''             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          bundler_ver: '>=0'         # Default is latest bundler version
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR

  notion-sync:
  stage: deploy
  script:
    - |
      # run our synchronization command
      bundle exec jekyll prefetch
      
      # if there are any changes from notion ...
      # note: be sure that all files produced by 
      #       (i.e. bundle install) are git-ignored
      if [[ $(git status --porcelain) ]]; then
        git config user.name "$BOT_NAME"
        git config user.email "$BOT_EMAIL"
        git add .
        git commit -m "Notion sync $(date +'%Y-%m-%d')"
        
        # git remote add ci "https://$TOKEN_NAME:$ACCESS_TOKEN@gitlab.com/<username>/<your-repo>.git"
        git push ci HEAD:$CI_COMMIT_REF_NAME
      fi
  only:
    - push
  variables:
    NOTION_TOKEN: $NOTION_TOKEN
